package com.polygres.wire.orawire.frontend;

import com.polygres.wire.orawire.ttc.TtcReader;
import com.polygres.wire.orawire.ttc.TtcWriter;
import com.polygres.wire.orawire.wireformat.TnsPacket;
import com.polygres.wire.orawire.wireformat.TnsPacketReader;
import com.polygres.wire.orawire.wireformat.TnsPacketType;
import java.io.IOException;
import java.io.OutputStream;

public final class ProtocolNegotiation {

    private static final int MSG_TYPE_PROTOCOL = 1;
    private static final int MSG_TYPE_DATA_TYPES = 2;
    
    private static final int MSG_TYPE_PROTOCOL_EXTENDED =
        com.polygres.wire.orawire.ttc.TtcConstants.MSG_TYPE_PROTOCOL_EXTENDED;

    private boolean pythonThinClient;

    private boolean extendedProtocol;

    public void perform(TnsPacketReader reader, OutputStream out) throws IOException {
        readProtocolRequest(reader);
        sendProtocolResponse(out, reader.isLargeSdu());
        readDataTypesRequest(reader);
        sendDataTypesResponse(out, reader.isLargeSdu());
    }

    private void readProtocolRequest(TnsPacketReader reader) throws IOException {
        TnsPacket packet = reader.readPacket();
        TtcReader r = new TtcReader(packet.payload());
        int msgType = r.readUint8();
        if (msgType == MSG_TYPE_PROTOCOL_EXTENDED) {
            extendedProtocol = true;
            r.skip(9);
        } else if (msgType == MSG_TYPE_PROTOCOL) {
            extendedProtocol = false;
            r.readUint8();
            r.readUint8();
        } else {
            throw new IOException("expected PROTOCOL message, got type " + msgType);
        }
        
        StringBuilder driverName = new StringBuilder();
        int b;
        while ((b = r.readUint8()) != 0) {
            driverName.append((char) b);
        }
        pythonThinClient = driverName.toString().toLowerCase(java.util.Locale.ROOT).contains("python-oracledb");
        
    }

    private static final String PROTOCOL_RESPONSE_B64 =
        "AQYATGludXgzOTB4L0xpbnV4LTIuNC54AGkDIQoAZgNAAwFAA2YDAWYDSAMBSANmAwFmA1IDAVIDZgMBZgNhAwFhA2YDAWYDHwMIHwNmAwEAZAAAAGABJA8FCwwDDAwFBAUNBgkHCAUFBQUFDwUFBQUFCgUFBQUFBAUGBwgII0cjRwgRIwgRQbBHAIMDaQfQAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2BgEBAe8PARsBAQEBAQEBf/8DEAMDAQH/Af//AQ4BAf8BBgz2CX8FD/8NCwD/AwAAAAAABwICDQIBAAEYAH8BAgAAAAA=";

    private static final String PROTOCOL_RESPONSE_EXTENDED_B64 =
        "HAEIAExpbnV4MzkweC9MaW51eC0yLjQueABpAwEKAGYDQAMBQANmAwFmA0gDAUgDZgMBZgNSAwFSA2YDAWYDYQMBYQNm"
            + "AwFmAx8DCB8DZgMBAGQAAABgASQPBQsMAwwMBQQFDQYJBwgFBQUFBQ8FBQUFBQoFBQUFBQQFBgcICCNHI0cIESMIEUGw"
            + "RwCDA2kH0AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANgYBAQHvDwEbAQEBAQEBAX//AxADAwEB"
            + "/wH//wEOAQH/AQYM9gl/BQ//DQsA/wMAAAAAAAcCAg0CAQABGAB/AQIAAAAAAQ==";

    private void sendProtocolResponse(OutputStream out, boolean largeSdu) throws IOException {
        byte[] payload = java.util.Base64.getDecoder()
                .decode(extendedProtocol ? PROTOCOL_RESPONSE_EXTENDED_B64 : PROTOCOL_RESPONSE_B64);
        sendData(out, payload, largeSdu);
    }

    private void readDataTypesRequest(TnsPacketReader reader) throws IOException {
        
        TnsPacket packet = reader.readPacket();
        while (packet.payload().length == 0) {
            packet = reader.readPacket();
        }
        TtcReader r = new TtcReader(packet.payload());
        int msgType = r.readUint8();
        if (msgType != MSG_TYPE_DATA_TYPES) {
            throw new IOException("expected DATA_TYPES message, got type " + msgType);
        }
        
    }

    private static final String DATA_TYPES_RESPONSE_B64 =
        "AgABAAEAAQAAAAIAAgAKAAAACAAIAAEAAAAMAAwACgAAABcAFwABAAAAGAAYAAEAAAAZABkAAQAAABoAGgABAAAAGwAbAAEAAAAcABwAAQAAAB0AHQABAAAAHgAeAAEAAAAfAB8AAQAAACAAIAABAAAAIQAhAAEAAAAKAAoAAQAAAAsACwABAAAAKAAoAAEAAAApACkA" +
        "AQAAAHUAdQABAAAAeAB4AAEAAAEiASIAAQAAASMBIwABAAABJAEkAAEAAAElASUAAQAAASYBJgABAAABKgEqAAEAAAErASsAAQAAASwBLAABAAABLQEtAAEAAAEuAS4AAQAAAS8BLwABAAABMQExAAEAAAEyATIAAQAAATMBMwABAAABNAE0AAEAAAE1ATUAAQAAATYB" +
        "NgABAAABNwE3AAEAAAE4ATgAAQAAATkBOQABAAABOwE7AAEAAAE8ATwAAQAAAT0BPQABAAABPgE+AAEAAAE/AT8AAQAAAUABQAABAAABQQFBAAEAAAFCAUIAAQAAAUMBQwABAAABRwFHAAEAAAFIAUgAAQAAAUkBSQABAAABSwFLAAEAAAFNAU0AAQAAAVMBUwABAAAB" +
        "VAFUAAEAAAFVAVUAAQAAAVYBVgABAAABVwFXAAEAAAFYAVgAAQAAAVkBWQABAAABWgFaAAEAAAFcAVwAAQAAAV0BXQABAAABYgFiAAEAAAFjAWMAAQAAAWcBZwABAAABawFrAAEAAAF8AXwAAQAAAX0BfQABAAABfgF+AAEAAAGAAYAAAQAAAYEBgQABAAABggGCAAEA" +
        "AAGDAYMAAQAAAYQBhAABAAABhQGFAAEAAAGGAYYAAQAAAYcBhwABAAABiQGJAAEAAAGKAYoAAQAAAYsBiwABAAABjAGMAAEAAAGNAY0AAQAAAY4BjgABAAABjwGPAAEAAAGQAZAAAQAAAZEBkQABAAABlAGUAAEAAAGVAZUAAQAAAZYBlgABAAABlwGXAAEAAAGdAZ0A" +
        "AQAAAZ4BngABAAABnwGfAAEAAAGgAaAAAQAAAaEBoQABAAABogGiAAEAAAGjAaMAAQAAAaQBpAABAAABpQGlAAEAAAGmAaYAAQAAAacBpwABAAABqAGoAAEAAAGpAakAAQAAAaoBqgABAAABqwGrAAEAAAGtAa0AAQAAAa4BrgABAAABrwGvAAEAAAGwAbAAAQAAAbEB" +
        "sQABAAABwQHBAAEAAAHCAcIAAQAAAcYBxgABAAABxwHHAAEAAAHIAcgAAQAAAckByQABAAABygHKAAEAAAHLAcsAAQAAAcwBzAABAAABzQHNAAEAAAHOAc4AAQAAAc8BzwABAAAB0gHSAAEAAAHTAdMAAQAAAdQB1AABAAAB1QHVAAEAAAHWAdYAAQAAAdcB1wABAAAB" +
        "2AHYAAEAAAHZAdkAAQAAAdoB2gABAAAB2wHbAAEAAAHcAdwAAQAAAd0B3QABAAAB3gHeAAEAAAHfAd8AAQAAAeAB4AABAAAB4QHhAAEAAAHiAeIAAQAAAeMB4wABAAAB5AHkAAEAAAHlAeUAAQAAAeYB5gABAAAB6gHqAAEAAAHrAesAAQAAAewB7AABAAAB7QHtAAEA" +
        "AAHuAe4AAQAAAe8B7wABAAAB8AHwAAEAAAHyAfIAAQAAAfMB8wABAAAB9AH0AAEAAAH1AfUAAQAAAfYB9gABAAAB/QH9AAEAAAH+Af4AAQAAAgECAQABAAACAgICAAEAAAIEAgQAAQAAAgUCBQABAAACBgIGAAEAAAIHAgcAAQAAAggCCAABAAACCQIJAAEAAAIKAgoA" +
        "AQAAAgsCCwABAAACDAIMAAEAAAINAg0AAQAAAg4CDgABAAACDwIPAAEAAAIQAhAAAQAAAhECEQABAAACEgISAAEAAAITAhMAAQAAAhQCFAABAAACFQIVAAEAAAIWAhYAAQAAAhcCFwABAAACGAIYAAEAAAIZAhkAAQAAAhoCGgABAAACGwIbAAEAAAIfAh8AAQAAAiAA" +
        "AAIhAAACIgAAAiMAAAIkAAACJQAAAiYAAAInAAACKAAAAikAAAIqAAACKwAAAiwAAAItAAACLgAAAi8AAAIwAjAAAQAAAjEAAAIyAAACMwIzAAEAAAI0AjQAAQAAAjYAAAI3AAACOAAAAjkAAAI6AAACOwAAAjwCPAABAAACPQI9AAEAAAI+Aj4AAQAAAj8CPwABAAAC" +
        "QAJAAAEAAAJBAAACQgJCAAEAAAJDAkMAAQAAAkQCRAABAAACRQJFAAEAAAJGAkYAAQAAAkcCRwABAAACSAJIAAEAAAJJAkkAAQAAAkoAAAJLAAACTAAAAk0AAAJOAk4AAQAAAk8CTwABAAACUAJQAAEAAAJRAlEAAQAAAlICUgABAAACUwJTAAEAAAJUAlQAAQAAAlUC" +
        "VQABAAACVgJWAAEAAAJXAlcAAQAAAlgCWAABAAACWQJZAAEAAAJaAloAAQAAAlsCWwABAAACXAJcAAEAAAJdAl0AAQAAAmMCYwABAAACZAJkAAEAAAJlAmUAAQAAAmYCZgABAAACZwJnAAEAAAJoAmgAAQAAAmkCaQABAAACbQAAAm4CbgABAAACbwJvAAEAAAJwAnAA" +
        "AQAAAnECcQABAAACcgJyAAEAAAJzAnMAAQAAAnQCdAABAAACdQJ1AAEAAAJ2AnYAAQAAAncCdwABAAACeAJ4AAEAAAJ5AAACegAAAnsAAAJ8AnwAAQAAAn0CfQABAAACfgJ+AAEAAAJ/An8AAQAAAoACgAABAAACgQAAAoIAAAKDAAAChAAAAoUAAAKGAoYAAQAAAocC" +
        "hwABAAACiAKIAAEAAAKJAAACigAAAosAAAKMAowAAQAAAo0CjQABAAACjwAAApACkAABAAACkQAAApIAAAKTAAAClAKUAAEAAAKVApUAAQAAApYAAAKXApcAAQAAApgAAAKZApkAAQAAApoAAAKcAAACnQAAAp4AAAADAAIACgAAAAQAAgAKAAAABQABAAEAAAAGAAIA" +
        "CgAAAAcAAgAKAAAACQABAAEAAAANAAAADgAAAA8AFwABAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAACcAAAA6AAAARAACAAoAAABFAAAARgAAAEoAAABMAAAAWwACAAoAAABeAAEAAQAAAF8AFwABAAAAYABgAAEAAABhAGAAAQAAAGQAZAABAAAAZQBlAAEA" +
        "AABmAGYAAQAAAGgAAABpAAAAagBqAAEAAABsAG0AAQAAAG0AbQABAAAAbgBvAAEAAABvAG8AAQAAAHAAcAABAAAAcQBxAAEAAAByAHIAAQAAAHMAAAB0AGYAAQAAAHYAAAB3AHcAAQAAAHkAAAB6AAAAewAAAH8AfwABAAAAiAAAAJIAkgABAAAAkwAAAJgAAgAKAAAA" +
        "mQACAAoAAACaAAIACgAAAJsAAQABAAAAnAAMAAoAAACsAAIACgAAALIAsgABAAAAswCzAAEAAAC0ALQAAQAAALUAtQABAAAAtgC2AAEAAAC3ALcAAQAAALgADAAKAAAAuQAAALoAAAC7AAAAvAAAAL0AAAC+AAAAvwAAAMAAAADDAHAAAQAAAMQAcQABAAAAxQByAAEA" +
        "AADGAHcAAQAAAMcAAADQANAAAQAAANEAAADnAOcAAQAAAOgA5wABAAAA6QDpAAEAAADxAG0AAQAAAPUAAAD2AAAA+gAAAPsAAAD8APwAAQAAAgMAAAAA";

    private static final String DATA_TYPES_RESPONSE_EXTENDED_B64 =
        "AoAAAAA8PDyAAAAAAAAALQABAAEAAQAAAAIAAgAKAAAACAAIAAEAAAAMAAwACgAAABcAFwABAAAAGAAYAAEAAAAZABkAGAAAABoA" +
        "GgAZAAAAGwAbAAoAAAAcABwAFgAAAB0AHQAXAAAAHgAeABcAAAAfAB8AGQAAACAAIAAMAAAAIQAhAAwAAAAKAAoAAQAAAAsACwAB" +
        "AAAAKAAoAAEAAAApACkAAQAAAHUAdQABAAAAeAB4AAEAAAEiASIAAQAAASMBIwABAAABJAEkAAEAAAElASUAAQAAASYBJgABAAAB" +
        "KgEqAAEAAAErASsAAQAAASwBLAABAAABLQEtAAEAAAEuAS4AAQAAAS8BLwABAAABMQExAAEAAAEyATIAAQAAATMBMwABAAABNAE0" +
        "AAEAAAE1ATUAAQAAATYBNgABAAABNwE3AAEAAAE4ATgAAQAAATkBOQABAAABOwE7AAEAAAE8ATwAAQAAAT0BPQABAAABPgE+AAEA" +
        "AAE/AT8AAQAAAUABQAABAAABQQFBAAEAAAFCAUIAAQAAAUMBQwABAAABRwFHAAEAAAFIAUgAAQAAAUkBSQABAAABSwFLAAEAAAFN" +
        "AU0AAQAAAVMBUwABAAABVAFUAAEAAAFVAVUAAQAAAVYBVgABAAABVwFXAAEAAAFYAVgAAQAAAVkBWQABAAABWgFaAAEAAAFcAVwA" +
        "AQAAAV0BXQABAAABYgFiAAEAAAFjAWMAAQAAAWcBZwABAAABawFrAAEAAAF8AXwAAQAAAX0BfQABAAABfgF+AAEAAAGAAYAAAQAA" +
        "AYEBgQABAAABggGCAAEAAAGDAYMAAQAAAYQBhAABAAABhQGFAAEAAAGGAYYAAQAAAYcBhwABAAABiQGJAAEAAAGKAYoAAQAAAYsB" +
        "iwABAAABjAGMAAEAAAGNAY0AAQAAAY4BjgABAAABjwGPAAEAAAGQAZAAAQAAAZEBkQABAAABlAGUAAEAAAGVAZUAAQAAAZYBlgAB" +
        "AAABlwGXAAEAAAGdAZ0AAQAAAZ4BngABAAABnwGfAAEAAAGgAaAAAQAAAaEBoQABAAABogGiAAEAAAGjAaMAAQAAAaQBpAABAAAB" +
        "pQGlAAEAAAGmAaYAAQAAAacBpwABAAABqAGoAAEAAAGpAakAAQAAAaoBqgABAAABqwGrAAEAAAGtAa0AAQAAAa4BrgABAAABrwGv" +
        "AAEAAAGwAbAAAQAAAbEBsQABAAABwQHBAAEAAAHCAcIAAQAAAcYBxgABAAABxwHHAAEAAAHIAcgAAQAAAckByQABAAABygHKAAEA" +
        "AAHLAcsAAQAAAcwBzAABAAABzQHNAAEAAAHOAc4AAQAAAc8BzwABAAAB0gHSAAEAAAHTAdMAAQAAAdQB1AABAAAB1QHVAAEAAAHW" +
        "AdYAAQAAAdcB1wABAAAB2AHYAAEAAAHZAdkAAQAAAdoB2gABAAAB2wHbAAEAAAHcAdwAAQAAAd0B3QABAAAB3gHeAAEAAAHfAd8A" +
        "AQAAAeAB4AABAAAB4QHhAAEAAAHiAeIAAQAAAeMB4wABAAAB5AHkAAEAAAHlAeUAAQAAAeYB5gABAAAB6gHqAAEAAAHrAesAAQAA" +
        "AewB7AABAAAB7QHtAAEAAAHuAe4AAQAAAe8B7wABAAAB8AHwAAEAAAHyAfIAAQAAAfMB8wABAAAB9AH0AAEAAAH1AfUAAQAAAfYB" +
        "9gABAAAB/QH9AAEAAAH+Af4AAQAAAgECAQABAAACAgICAAEAAAIEAgQAAQAAAgUCBQABAAACBgIGAAEAAAIHAgcAAQAAAggCCAAB" +
        "AAACCQIJAAEAAAIKAgoAAQAAAgsCCwABAAACDAIMAAEAAAINAg0AAQAAAg4CDgABAAACDwIPAAEAAAIQAhAAAQAAAhECEQABAAAC" +
        "EgISAAEAAAITAhMAAQAAAhQCFAABAAACFQIVAAEAAAIWAhYAAQAAAhcCFwABAAACGAIYAAEAAAIZAhkAAQAAAhoCGgABAAACGwIb" +
        "AAEAAAIfAh8AAQAAAiACIAABAAACIQIhAAEAAAIiAiIAAQAAAiMCIwABAAACJAIkAAEAAAIlAiUAAQAAAiYCJgABAAACJwInAAEA" +
        "AAIoAigAAQAAAikCKQABAAACKgIqAAEAAAIrAisAAQAAAiwCLAABAAACLQItAAEAAAIuAi4AAQAAAi8CLwABAAACMAIwAAEAAAIx" +
        "AjEAAQAAAjICMgABAAACMwIzAAEAAAI0AjQAAQAAAjYCNgABAAACNwI3AAEAAAI4AjgAAQAAAjkCOQABAAACOgI6AAEAAAI7AjsA" +
        "AQAAAjwCPAABAAACPQI9AAEAAAI+Aj4AAQAAAj8CPwABAAACQAJAAAEAAAJBAkEAAQAAAkICQgABAAACQwJDAAEAAAJEAkQAAQAA" +
        "AkUCRQABAAACRgJGAAEAAAJHAkcAAQAAAkgCSAABAAACSQJJAAEAAAJKAkoAAQAAAksCSwABAAACTAJMAAEAAAJNAk0AAQAAAk4C" +
        "TgABAAACTwJPAAEAAAJQAlAAAQAAAlECUQABAAACUgJSAAEAAAJTAlMAAQAAAlQCVAABAAACVQJVAAEAAAJWAlYAAQAAAlcCVwAB" +
        "AAACWAJYAAEAAAJZAlkAAQAAAloCWgABAAACWwJbAAEAAAJcAlwAAQAAAl0CXQABAAACYwJjAAEAAAJkAmQAAQAAAmUCZQABAAAC" +
        "ZgJmAAEAAAJnAmcAAQAAAmgCaAABAAACaQJpAAEAAAJtAm0AAQAAAm4CbgABAAACbwJvAAEAAAJwAnAAAQAAAnECcQABAAACcgJy" +
        "AAEAAAJzAnMAAQAAAnQCdAABAAACdQJ1AAEAAAJ2AnYAAQAAAncCdwABAAACeAJ4AAEAAAJ5AnkAAQAAAnoCegABAAACewJ7AAEA" +
        "AAJ8AnwAAQAAAn0CfQABAAACfgJ+AAEAAAJ/An8AAQAAAoACgAABAAACgQKBAAEAAAKCAoIAAQAAAoMCgwABAAAChAKEAAEAAAKF" +
        "AoUAAQAAAoYChgABAAAChwKHAAEAAAKIAogAAQAAAokCiQABAAACigKKAAEAAAKLAosAAQAAAowCjAABAAACjQKNAAEAAAKPAo8A" +
        "AQAAApACkAABAAACkQKRAAEAAAKSApIAAQAAApMCkwABAAAClAKUAAEAAAKVApUAAQAAApYClgABAAAClwKXAAEAAAKYApgAAQAA" +
        "ApkCmQABAAACmgKaAAEAAAKcApwAAQAAAp0CnQABAAACngKeAAEAAAADAAIACgAAAAQAAgAKAAAABQABAAEAAAAGAAIACgAAAAcA" +
        "AgAKAAAACQABAAEAAAANAAAADgAAAA8AFwABAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAACcAAAA6ADoAAQAAAEQAAgAK" +
        "AAAARQAAAEYAAABKAG0AAQAAAEwAAABbAAIACgAAAF4AAQABAAAAXwAXAAEAAABgAGAAAQAAAGEAYAABAAAAZABkAAEAAABlAGUA" +
        "AQAAAGYAZgABAAAAaAAAAGkAAABqAGoAAQAAAGwAbQABAAAAbQBtAAEAAABuAG8AAQAAAG8AbwABAAAAcABwAAEAAABxAHEAAQAA" +
        "AHIAcgABAAAAcwAAAHQAZgABAAAAdgAAAHcAdwABAAAAeQB5AAEAAAB6AHoAAQAAAHsAewABAAAAfwB/AAEAAACIAAAAkgCSAAEA" +
        "AACTAJMAAQAAAJgAAgAKAAAAmQACAAoAAACaAAIACgAAAJsAAQABAAAAnAAMAAoAAACsAAIACgAAALIAsgABAAAAswCzAAEAAAC0" +
        "ALQAAQAAALUAtQABAAAAtgC2AAEAAAC3ALcAAQAAALgADAAKAAAAuQCyAAEAAAC6ALMAAQAAALsAtAABAAAAvAC1AAEAAAC9ALYA" +
        "AQAAAL4AtwABAAAAvwAAAMAAAADDAHAAAQAAAMQAcQABAAAAxQByAAEAAADGAHcAAQAAAMcAfwABAAAA0ADQAAEAAADRAAAA5wDn" +
        "AAEAAADoAOcAAQAAAOkA6QABAAAA8QBtAAEAAAD1APUAAQAAAPYA9gABAAAA+gAAAPsAAAD8APwAAQAAAgMCAwABAAAAAA==";

    private void sendDataTypesResponse(OutputStream out, boolean largeSdu) throws IOException {
        byte[] payload;
        if (pythonThinClient) {
            payload = new byte[] { (byte) MSG_TYPE_DATA_TYPES, 0, 0 };
        } else if (extendedProtocol) {
            payload = java.util.Base64.getDecoder().decode(DATA_TYPES_RESPONSE_EXTENDED_B64);
        } else {
            payload = java.util.Base64.getDecoder().decode(DATA_TYPES_RESPONSE_B64);
        }
        sendData(out, payload, largeSdu);
    }

    private void sendData(OutputStream out, byte[] payload, boolean largeSdu) throws IOException {
        TnsPacket packet = new TnsPacket(TnsPacketType.DATA, 0, payload);
        out.write(packet.encode(largeSdu));
        out.flush();
    }
}
